### PR TITLE
Support for ArcCW

### PR DESCRIPTION
**Pull request by dhkatz**
These are preliminary changes, still testing them but should mostly work so far

### CODE REVIEW

**Comment by dhkatz** [comment]
This should also support any weapons that straight up don't provide any recoil, accuracy, or delay information by just defaulting to existing values.

**Comment by dhkatz** [comment]
Just tested in-game with a few bugs, fixing now

**Comment by TimGoll** [comment]
Thanks for your contribution!

**Comment by dhkatz** [comment]
Should be working now. I kinda had to make some arbitrary decisions regarding converting ArcCW's recoil and accuracy to the accuracy used in the checks.

If you think the conversion should be changed let me know. The accuracy conversion is pretty spot on from what I can tell but I'm a bit unsure of the recoil. Although it does seem mostly okay, at least with the weapons I tested from ArcCW

**Review by TimGoll — APPROVED** [review]

**Comment by TimGoll** [comment]
Thank you again for this contribution. I'm sorry it took so long to review this. I changed a few lines of your code to make them a bit more in line with our style

**Pull request merged**
